# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details

version: 2
jobs:
  build:
    working_directory: ~/turing_mentors_be
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.5-stretch
        environment:
          BUNDLER_VERSION: 2.0.1
          PGHOST: localhost
          PGUSER: turing_mentors_be
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: turing_mentors_be
          POSTGRES_DB: turing_mentors_be_test
          POSTGRES_PASSWORD: ""

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler
            bundle update rails
            bundle install
      - run: bundle exec rake db:{drop,create,migrate,seed}
      - run: bundle exec rake db:schema:load

      - run: bundle exec rspec
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:cdf62201-c16c-4042-8008-3df2c367f08b@git.heroku.com/$turing-mentors-be.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
